version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  destroy-lambda:
    description: "Destroy API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless@^3
      - run:
          name: Build lambda
          command: |
            cd ./ResidentContactApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy or Destroy lambda
          command: |
            cd ./ResidentContactApi/
            sls remove --stage <<parameters.stage>> --verbose
jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build resident-contact-api-test
      - run:
          name: Run tests
          command: docker-compose run resident-contact-api-test
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  deploy-to-production:
    executor: docker-dotnet
    steps:
      - destroy-lambda:
          stage: "production"
workflows:
  feature-workflow:
    jobs:
      - check-code-formatting:
          filters:
            branches:
              ignore: master
      - build-and-test:
          requires:
            - check-code-formatting
          filters:
            branches:
              ignore: master
  check-and-deploy-production:
    jobs:
      - check-code-formatting:
          filters:
            branches:
              only: master
      - build-and-test:
          requires:
            - check-code-formatting
          filters:
            branches:
              only: master
      - assume-role-production:
          context: api-assume-role-production-context
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - permit-production-release:
          type: approval
          requires:
            - assume-role-production
          filters:
            branches:
              only: master
      - deploy-to-production:
          requires:
            - permit-production-release
            - assume-role-production
          filters:
            branches:
              only: master
